services:
  api:
    build: 
      context: .         # Context Ã  la racine du projet
      dockerfile: Dockerfile.dev  # Dockerfile dans docker/
    container_name: calculator-api-dev
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=debug
      - PORT=8080